services:
  - type: web
    name: gym-backend
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DB_HOST
        value: mysql-xxxx.render.com  # à modifier
      - key: DB_USER
        value: root                   # à modifier
      - key: DB_PASSWORD
        value: ton_password_mysql    # à modifier
      - key: DB_NAME
        value: salle_sport_POWERGYMNEFTA
      - key: JWT_SECRET
        value: cle_secrete_super
