services:
  - type: web
    name: gym-backend
    env: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DB_HOST
        value: mysql-xxxxx.render.com  # Remplace par l'adresse réelle Render de ta base
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: mot_de_passe
      - key: DB_NAME
        value: salle_sport_POWERGYMNEFTA
      - key: JWT_SECRET
        value: cle_secrete_super
