services:
  - type: web
    name: backend-gymnefta
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DB_HOST
        value: ton_host
      - key: DB_USER
        value: ton_utilisateur
      - key: DB_PASSWORD
        value: ton_mot_de_passe
      - key: DB_NAME
        value: salle_sport_POWERGYMNEFTA
      - key: JWT_SECRET
        value: cle_secrete_super
